### PR TITLE
Fix fingerprint.template formatting

### PR DESCRIPTION
**Pull request by toolboc**
fingerprint.template failed to produce valid access token as-is.  Reformatting allows for easier readability and proper access token creation.

### CODE REVIEW

**Comment by nickplee** [comment]
I'll take your word for it.

**Comment by ryanckulp** [comment]
@nickplee when this PR comment appeared in my inbox i spit out my coffee laughing

**Comment by nickplee** [comment]
Appropriate

**Comment by toolboc** [comment]
FWIW, pulling down the code as-is and supplying appropriate keyz did not produce a valid access token.  Ideally these changes should be confirmed in a clean test environment.  There may be more to the deviceFingerprint i.e. expiry or something.

**Comment by toolboc** [comment]
It seems that I have stumbled across the root cause:

When modifying fingerprint.template with my changes, I introduced a CR LF (carriage return / line-feed) at the end of the file, which contributed to the proper token generation.  Seems crazy right?

This was again verified when I took the changes from [Antoine De Chassey's fork ](https://github.com/AntoinedeChassey/Starbucks/commit/bdb7288f14f559a9c823574c56ed50b6f54047eb) and was again unable to generate a proper token.  [I modified his params ](https://github.com/toolboc/Starbucks/commit/f31c51587b4ccaea5825f06a3574aafdc63217a9) with an appended /r /n (CR LF), and was then able to produce a proper access token.

For what it is worth, appending a newline (/n only) also results in proper token generation.  This makes sense as this is included in the spec for [HTTP Header Line Breaks](https://stackoverflow.com/questions/5757290/http-header-line-break-style).  

I have reproduced this on two local machines, both running Windows 10 with latest version of Node etc.  I also had to make these changes in order to properly run on a hosted instance.

The question is why am I getting this issue in the first place?  Could it be a platform discrepancy, something to do with the way axios sends the data portion of a web request, or something else?

**Comment by nickplee** [comment]
My money's on us not knowing something about the request format expected by the server. This whole API is a tangled mess of security-by-obscurity.

**Comment by toolboc** [comment]
^Agreed

**Comment by toolboc** [comment]
(CR LF) / (\r\n) issue properly resolved in #2

**Pull request merged**
